version: '3'
services:

  # maps any service with a VIRTUAL_HOST env variable to the specified host 
  soe-nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - soe-network
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      #- "nginx_certs:/etc/nginx/certs:rw"

  soe-web-ngrok:
    image: wernight/ngrok
    networks:
      - soe-network
    depends_on:
      - soe-nginx-proxy
    environment:
      NGROK_AUTH: ${NGROK_AUTH}
      NGROK_SUBDOMAIN: sgs
      NGROK_LOOK_DOMAIN: soe-nginx

  soe-embedded-ngrok:
    image: wernight/ngrok
    networks:
      - soe-network
    depends_on:
      - soe-embedded
    environment:
      NGROK_AUTH: ${NGROK_AUTH}
      NGROK_SUBDOMAIN: embedded-sgs
      NGROK_PORT: 3000
      NGROK_LOOK_DOMAIN: soe-embedded

  # Nginx Service
  soe-nginx:
    image: nginx:alpine
    container_name: soe-nginx
    restart: unless-stopped
    tty: true
    networks:
      - soe-network
    volumes:
      - ./web:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    environment:
      VIRTUAL_HOST: soe.localhost
    depends_on:
      - soe-embedded
      - soe-web

  # PHP Service
  soe-web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: soe-web
    container_name: soe-web 
    restart: unless-stopped
    tty: true
    environment:
      DB_HOST: soe-db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SESSION_DOMAIN: .localhost
      APP_URL: ${APP_URL}
      EMBEDDED_URL: ${EMBEDDED_URL}
      NYLAS_CLIENT_ID: ${NYLAS_CLIENT_ID}
      NYLAS_CLIENT_SECRET: ${NYLAS_CLIENT_SECRET}
      SOE_API_PASSWORD: ${SOE_API_PASSWORD}
      SOE_SHOP_PASSWORD: ${SOE_SHOP_PASSWORD}
    working_dir: /var/www
    networks:
      - soe-network
    volumes:
      - ./web:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - soe-db
      - soe-db-test

  # Node/NextJS service
  soe-embedded:
    build: 
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: sh -c "npm run dev"
    env_file: ./embedded/.env
    environment:
      VIRTUAL_HOST: embedded.soe.localhost
      HOST: ${EMBEDDED_URL}  
      APP_URL: ${APP_URL}
      EMBEDDED_URL: ${EMBEDDED_URL}
      NYLAS_CLIENT_ID: ${NYLAS_CLIENT_ID}
      SOE_API_PASSWORD: ${SOE_API_PASSWORD}
      PORT: 3000
    container_name: soe-embedded
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - soe-network
    volumes:
      - ./embedded:/var/www
      #- /var/www/node_modules
    command: ["npm", "run", "dev"]

  # MySQL Service
  soe-db:
    image: mysql:8.0.21
    container_name: soe-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - soe-network
    volumes:
      - soe-dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  soe-db-test:
    image: mysql:8.0.21
    container_name: soe-db-test
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - soe-network
    volumes:
      - soe-dbdata-test:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  soe-mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
          - 1025:1025
          - 8025:8025
      networks:
          - soe-network


# Docker Networks
networks:
  soe-network:
    driver: bridge

# Volumes
volumes:
  soe-dbdata:
    driver: local
  soe-dbdata-test:
    driver: local